### ISSUE TITLE
Scaffolding Obscures Actual Types

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [JordanMartinez/learn-halogen#44] opened 2019-09-15 12:21 UTC
I am going through some of the lessons and there seem to be a lot of types aliases that obscure the actual type. Thus I go to the scaffolding module and find what it actually is and then flip back and forth between the pages until I memorize what the alias actually is.

Would it not be better to use the actual types, put the aliases in the same file, or use a comment for the aliases?

Example `StateActionMessageComponent`:

https://github.com/JordanMartinez/learn-halogen/blob/951f7c33ae138deea667ef171d13fb7a5e32f4de/src/03-Parent-Child-Relationships/01-Childlike-Components/04-Message-Only.purs#L28

**Comment by JordanMartinez** [comment] 2019-09-16 19:38
@BebeSparkelSparkel Yeah, that's the general conclusion we've reached in #42 (this issue is a duplicate of that one). I'll likely be swithcing to that new approach this week, so it might be best to wait until I finish that.

**Closed as completed by JordanMartinez** 2019-09-16 19:38 UTC
Labels: duplicate

**Comment by BebeSparkelSparkel** [comment] 2019-09-16 21:57
Ok
